### ISSUE TITLE
Suggestion: A parser for a sdjwt string without the need of suspension.

### ISSUE THREAD

**Issue by goncalo-frade-iohk** [eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt#200]
Hey. I have a suggestion that I found can be a good utility.

As a developer I may want to process an SDJWT without verifying.

Having a helper function that would initialise a holder SdJwt<JWT>, would simplify this process.
This way I could initialise a SdJWT without the need of having a suspended function.

This would be very useful when as a holder you want to process the claims of a saved SDJwt without the need of verifying it again.
I understand there is `JwtSignatureVerifier.Companion.NoSignatureValidation` but it still requires to be `suspended`.

I opened a PR with this in mind: https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/pull/201

```
object SdJwtVerifier {

    /**
     * Parses an SD-JWT to extract the JWT and its claims.
     *
     * This function takes an unverified SD-JWT, parses it to separate the JWT and its disclosures,
     * and then constructs an issuance object containing the JWT and its claims along with the unique disclosures.
     *
     * @param unverifiedSdJwt the unverified SD-JWT to be parsed
     * @return an issuance object containing the JWT and its claims, and the unique disclosures
     */
    fun sdJWTParser(unverifiedSdJwt: String): SdJwt.Issuance<JwtAndClaims> {
        val (unverifiedJwt, unverifiedDisclosures) = parseIssuance(unverifiedSdJwt)
        val parsedJwt = SignedJWT.parse(unverifiedJwt)
        val jwtClaims = parsedJwt.jwtClaimsSet.asClaims()
        val disclosures = uniqueDisclosures(unverifiedDisclosures)
        return SdJwt.Issuance(unverifiedJwt to jwtClaims, disclosures)
    }
...
}
```

**Comment by goncalo-frade-iohk** [comment]
https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/pull/201

**Comment by babisRoutis** [comment]
Dear @goncalo-frade-iohk 
Thanks for the suggestion and the PR.

Before examining the PR, may I ask what is the problem with calling a suspended function?

If I am not mistaken there is always the option to call a suspending function from a non suspending code, provided that you wrap the former in a `runBlocking` code.

For instance, something like the code bellow

```kotlin

fun load(storedSdJwt: String): SdJwt.Issuance<JwtAndClaims> = runBlocking {
   val noValidation = JwtSignatureVerifier.NoSignatureValidation
   SdJwtVerifier.verifyIssuance(noValidation, storedSdJwt).getOrThrow()
}
```

**Comment by goncalo-frade-iohk** [comment]
Hi @babisRoutis,
Thanks for your response.

Yes, I’m currently using `runBlocking` as a workaround, but I believe that the API should accurately reflect its intended use. In this specific use case (that IMO will be used a lot), there isn’t a requirement for a suspended method.

While using runBlocking works and we know that with NoSignatureValidation it will always provide a quick response, the API should ideally be straightforward and reflect the nature of the task. There is also the potential (even though it might seem far-fetched in this case) that the implementation of NoSignatureValidation could change in the future to include a suspended behaviour. Such a change wouldn’t necessarily be considered a breaking change and might not trigger a version update.

If this were to happen and the `runBlocking` is used on the main thread, it could unexpectedly block the UI, causing performance issues. Therefore, having a non-suspending function for this use case would make the API more robust and user-friendly, preventing any unintended side effects.

Thank you for considering this perspective.

**Comment by babisRoutis** [comment]
Dear @goncalo-frade-iohk 

I also believe that the API should reflect its intend use and to my (subjective :smile:) understanding it does.  

I think that the method that you propose to be added is not relevant to the `SdJwtVerifier`. 

It probably addresses a different problem, that is to skip verification and instantiate an `SdJwt.Issuance`. 
You already mention a possible reason (wallet has already verified this), which sounds reasonable.

Perhaps this can be done in another way, for instance a new class `UnsafeLoader` or add an `unsafeFrom(jwt: String)` to the companion object of SdJwt.Issuance. I will try to provide some concrete comments/directions in the context of the PR

**Comment by goncalo-frade-iohk** [comment]
Hi @babisRoutis .

Totally agree with you, this code belongs on other place.

**Comment by babisRoutis** [comment]
Hi @goncalo-frade-iohk 
Please check your PR. I have provided some guidelines. Let's continue there if you don't mind
