### ISSUE TITLE
Validating an EdDSA signed SD-JWT fails

### ISSUE THREAD

**Issue by nemqe** [eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt#229]
I noticed that when using Ed25519 keys in their JWK form (`com.nimbusds.jose.jwk.OctetKeyPair`) the key selector does not find the key in question and the verification of the SD-JWT fails with an `InvalidJwt` error.

The source of the issue seems to be that nimbus `JWSVerificationKeySelector` does not work well with asymmetric keys that are not `ECKey` or `RSAKey` because when we get a match for a JWT that represents a OKP key (Ed25519 in our case), converting the key to Java keys via `com.nimbusds.jose.jwk.KeyConverter.toJavaKeys` just silently ignores the key in question.

I do realize that this is mostly in the nimbus library but as sdjwt-kt relies on this logic I wondered if you ever had a similar issue, or if you have some advice on how to approach solving it.

Thanks!

**Comment by babisRoutis** [comment]
Hi @nemqe 

Thank you for reporting this, and especially for the analysis. 
We will  investigate if fix or workaround can be given within the sd-jwt library.

**Comment by babisRoutis** [comment]
Hi @nemqe 

If you will, please provide your comment on #230

**Comment by babisRoutis** [comment]
@nemqe FYI, fix [released](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/releases/tag/v0.6.3)

**Comment by nemqe** [comment]
@babisRoutis awesome, thank you!
