### ISSUE TITLE
JWK kid and DID interactions with Nimbus verifier

### ISSUE THREAD

**Issue by chumbert** [eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt#234]
When verifying SD-JWTs that have been signed with a DID's key, Nimbus' `JWSVerificationKeySelector` - and therefore the SD-JWT verifier - needs the JWK found in the DID document to have a `kid` that coincides with the JWT header's `kid` to properly select the verification key.

With the current SD-JWT specifications, the JWT `kid` needs to be of the form `did:method:identifier#keyId` to allow for key resolution by holders and verifiers. ([section 3.5](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-sd-jwt-vc-05#section-3.5))

Verification can still be achieved in two ways: 
* by embedding such a `kid` in the JWK representation of verification methods in the DID document. But this is not standard: it is not mandatory to set that `kid` and the specification RECOMMENDS using the IETF format for `kid`s which conflicts with what the SD JWT VC spec requires (see [did-core spec](https://w3c.github.io/did-core/#verification-material)).
* by altering the JWK to set the appropriate `kid`, but any manipulation of the JWK is a bit unsavory.

To use the library's verifier in this setting, the DID has to be resolved and the correct key extracted beforehand. Is there a way the key selector can be used with a pre-selected key ? If not, should the library offer a verification entry point that does not rely on Nimbus selecting the key that has already been resolved to avoid manipulation of key material ?

**Comment by babisRoutis** [comment]
Hi @chumbert 

Thanks for reporting this. We will look into it and get back to you.

As a quick comment, 

The library in the case of SD-JWT-VC offers a specialized verifier (`SdJwtVcVerifier`) which accepts an interface (or custom way) to resolve a DID (and optionally a DID URL) to one or more JWKs.
The interface is the following

```kotlin
fun interface LookupPublicKeysFromDIDDocument {

    /**
     * Lookup the public keys from a DID document.
     *
     * @param did the identifier of the DID document
     * @param didUrl optional DID URL, that is either absolute or relative to [did], indicating the exact public key
     * to lookup from the DID document
     *
     * @return the matching public keys or null in case lookup fails for any reason
     */
    suspend fun lookup(did: String, didUrl: String?): List<JWK>?
}
```

This is being used by the `SdJwtVcVerifier` in case the sd-jwt-vc to be validated contains a DID (and optional a DID URL) in the `kid`. Thus, I have the impression that there is no need to resolve beforehand the DID. 

In general, `SdJwtVcVerifier` tries to identify (from the given sd-jwt-vc) the source of the issuer's public key (metadata, x5c, did) and then tries to fetch it from that source. 
(https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/blob/0e890fbb8f01e49f627b9ad5ca95c7f0a4459929/src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt#L190)

**Comment by dzarras** [comment]
Hi @chumbert,

Thanks again for reporting this. 

Some quick comments:

> When verifying SD-JWTs that have been signed with a DID's key, Nimbus' `JWSVerificationKeySelector` - and therefore the SD-JWT verifier - needs the JWK found in the DID document to have a `kid` that coincides with the JWT header's `kid` to properly select the verification key.

Yes this is true. The `JWKSelector` used by `SdJwtVcJwtProcessor` expects to match the `kid` header claim to the `kid` claim of the JWK.

> Verification can still be achieved in two ways:
> 
> * by embedding such a `kid` in the JWK representation of verification methods in the DID document. But this is not standard: it is not mandatory to set that `kid` and the specification RECOMMENDS using the IETF format for `kid`s which conflicts with what the SD JWT VC spec requires (see [did-core spec](https://w3c.github.io/did-core/#verification-material)).

Correct, but as you state this is RECOMMENDED not MANDATED. Nothing prevents the structure of `kid` to be `did:method:identifier#keyId`. Even in [RFC7517](https://datatracker.ietf.org/doc/html/rfc7517) the structure of `kid` is unspecified. Check [Section 4.5](https://datatracker.ietf.org/doc/html/rfc7517#section-4.5).

> * by altering the JWK to set the appropriate `kid`, but any manipulation of the JWK is a bit unsavory.

This is one approach. You could use a `LookupPublicKeysFromDIDDocument` implementation that sets the appropriate `kid` value before returning the JWK. Ideally though, the correct `kid` should be set to the JWK in the DID Document Verification Method.

> To use the library's verifier in this setting, the DID has to be resolved and the correct key extracted beforehand. Is there a way the key selector can be used with a pre-selected key ? If not, should the library offer a verification entry point that does not rely on Nimbus selecting the key that has already been resolved to avoid manipulation of key material ?

I'm not really sure about this. The SD-JWT VC spec provides clear instructions on how signature verification must be performed. I don't like the idea of introducing a new entry point that bypasses these rules.

We'll look further into this and keep you posted.

Kind regards.

**Comment by babisRoutis** [comment]
Hi @chumbert 

I guess now we have a more clear understanding of the problem. 

I think we can prepare a branch (not yet a PR), that will actually remove the `kid` from the matching criteria that filter out the list of JWKs (after DID resolution). 
In this way, you  - as a caller - you can pass in whatever JWKs the resolution provides, without having to alter them.

It would be great if you could provide your comments to this solution (or even give it a try)

Please, let us know this sound to you

cc @dzarras

**Comment by dzarras** [comment]
@chumbert Could you please have a look at #235 and let us know of any comments?

**Comment by chumbert** [comment]
@dzarras thanks for the swift proposal. I think this would be perfect.

If you're not in a hurry to merge I can give it a try with our own code in the following days.

**Comment by dzarras** [comment]
> @dzarras thanks for the swift proposal. I think this would be perfect.
> 
> If you're not in a hurry to merge I can give it a try with our own code in the following days.

@chumbert Please do so. 
This is an initial implementation/proposal that we need to further check/consider before merging.
Thanks.

**Comment by chumbert** [comment]
Hello @dzarras 

I tested the change your propose in our code. Verification of SD-JWT passes even after I disabled our `kid` overwriting code.

Thanks for giving this attention.

**Comment by dzarras** [comment]
@chumbert 

SD-JWT v0.6.4, which includes the fix for this bug, has been released. 
https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/releases/tag/v0.6.4

It should be reaching Maven Central shortly.

Please let us know of any issues.
