### ISSUE TITLE
`SdJwtVcVerifier` must not always require KeyBinding JWT when verifying a presentation

### ISSUE THREAD

**Issue by dzarras** [eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt#293]
`SdJwtVcVerifier` contains two methods that can be used to verify a presentation:

```kotlin
suspend fun verifyPresentation(
        unverifiedSdJwt: String,
        challenge: JsonObject? = null,
    ): Result<Pair<SdJwt.Presentation<JwtAndClaims>, JwtAndClaims?>>
```

and 

```kotlin
suspend fun verifyPresentation(
        unverifiedSdJwt: JsonObject,
        challenge: JsonObject? = null,
    ): Result<Pair<SdJwt.Presentation<JwtAndClaims>, JwtAndClaims?>>
```

Internally they both use `KeyBindingVerifier.forSdJwtVc(challenge)` to get an instance of `KeyBindingVerifier.MustBePresentAndValid` to validate the KeyBinding JWT.

A first issue that arises is the return type being incorrect. Given that the KeyBinding JWT must be present and valid, both of these methods must return `Result<Pair<SdJwt.Presentation<JwtAndClaims>, JwtAndClaims>>` with the KeyBinding JWT part being non-nullable.

Finally, and most importantly, the KeyBinding JWT is not required even during presentation. Quoting from the [spec](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-08.html#section-4.1):

> If the presentation of the SD-JWT VC includes a Key Binding JWT, the Key Binding JWT MUST adhere to the rules defined in Section 4.3 of [[I-D.ietf-oauth-selective-disclosure-jwt](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-08.html#I-D.ietf-oauth-selective-disclosure-jwt)].

Fixing the later will most probably introduce breaking API changes.

**Comment by babisRoutis** [comment]
@dzarras  Good catch.

I suggest the following: 
- Correct the return type of the methods that you highlighted. Those would require the presence of KB-JWT 
- Consider introducing a new pair of methods that would enforce that no KB-JWT is present

**Comment by babisRoutis** [comment]
> Fixing the later will most probably introduce breaking API changes.

We already moved main branch to 0.10.0-SNAPSHOT, that will introduce breaking changes
