### ISSUE TITLE
Ensure `vct` claim is present for SD-JWT-VCs

### ISSUE THREAD

**Issue by dzarras** [eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt#294]
According to the [spec](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-08.html#section-3.2.2.2), `vct` is a claim that must be always present (not selectively disclosable) for SD-JWT-VCs.

Currently we only check for the presence of `iss`. [source](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/blob/main/src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcJwtProcessor.kt#L56)

**Comment by babisRoutis** [comment]
@dzarras Please add a fix for this and replace the hard-coded claim names with constants from the related object.
